version: '2'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'api-express-ts'
    ports:
      - '5432:5432'
    volumes:
      - './db-data:/var/lib/postgresql/data'